[project]
name = "open_pulse"
authors = [
  { name = "Eisha Tir Raazia", email = "eisha.raazia@epfl.ch" },
]
description = "Analyse performance of open source and hackathon repositories"
readme = "README.md"
requires-python = ">=3.13"
version = "0.0.1"

dependencies = [
    "pandas>=3.0.0",
    "pydantic>=2.10.6",
    "pytest>=8.4.2",
    "typer>=0.9.0",
    "requests>=2.31.0",
    "beautifulsoup4>=4.12.0",
    "huggingface-hub>=0.19.0",
    "python-dotenv>=1.0.0",
    "pyarrow>=15.0.0",
]
[dependency-groups]
dev = [
    "notebook>=7.3.2",
]

[project.scripts]
cli = 'open_pulse.cli:main'
hackalysis = 'hackathon_analysis.cli:app'

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
exclude = [
    ".direnv",
    ".devenv",
    ".output",
]

[tool.hatch.build.targets.wheel]
packages = ["src/open_pulse", "src/hackathon_analysis"]

[tool.ruff]
extend-include = ["*.ipynb"]
target-version = "py313"
line-length = 88

[tool.ruff.lint]
extend-select = [
    "W605",   # pycodestyle: invalid-escape-sequence
    "S102",   # flake8-bandit: exec-builtin
    "INP",    # flake8-no-pep420
    "PYI",    # flake8-pyi
    "PT",     # flake8-pytest-style
    "PGH",    # pygrep-hooks
    "PL",     # Pylint
    "NPY",    # NumPy-specific rules
    "RUF",    # Ruff-specific rules
]
ignore = [
    "NPY002", # numpy-legacy-random
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
"tests/**" = ["INP001"]
"[!t][!e][!s][!t][!s]*/**" = ["PT"]
