[server]
port = 8501
headless = true

[theme]
primaryColor = "#5561a6"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8fafc"
textColor = "#334155"
font = "sans serif"

[browser]
gatherUsageStats = false
