# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_src_path: src/python
module_name: open_pulse
project_authors:
-   email: eisha.raazia@epfl.ch
    first_name: Eisha
    last_name: Tir Raazia
project_description: Analyse performance of open source and hackathon repositories
project_url: https://github.com/sdsc-ordes/open-pulse-hackathon-analysis
project_version: 0.0.1
