name: format
on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      - name: install uv
        run: |
          python -m pip install --upgrade pip
          python -m pip install uv
      - name: format check
        run: |
          uv run ruff format --check src tests ||  
          {
            echo "You have not formatted these files: run 'uv run ruff format src tests' locally!"
            echo "============================================================="
            git diff --name-only
            echo "============================================================="
          }
